# Generated by Django 5.0.2 on 2025-12-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "type",
                    models.CharField(
                        choices=[("BARBER", "Barbeiro"), ("CLIENT", "Cliente")],
                        max_length=10,
                        verbose_name="Tipo de usuário",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atualizado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["-created_at"],
            },
        ),
    ]
